### PR TITLE
fix: working note taking and deletion

### LINKED ISSUE #833: Bug: Deleting a repo was presented with a failure due to protected branch permissions
### Describe the bug
Deleting a repo was presented with a failure due to protected branch permissions

### To Reproduce

Deleting a repo was presented with a failure due to protected branch permissions

1. Add a repo ...wait for it to show #832 
2. Delete the repo
3. Visit your goals repo to see if it was removed

https://github.com/bdougie/open-sauced-goals/runs/1169979951?check_suite_focus=true#step:6:13

### Expected behavior

There might need to be a local cache or local storage that removes the repo right away. The Action that powers the deletion should work as well.

### LINKED ISSUE #955: Bug: taking notes does not work
### To Reproduce

1. go to the dashboard
1. add any repository
1. click to view added repository
1. add a note
1. check the network tab
1. github request returned an error

### Expected behavior

Taking notes should work:
- added notes should exist on the "open-sauced-goals" repository as issues
- visually, after refresh the notes should still be there

### Screenshots

Sample JSON of the responses when querying:

```json
{
    "errors": [{
        "message": "Variable $id of type ID! was provided invalid value",
        "path": ["gitHub"],
        "extensions": {
            "service": "github",
            "upstream": {
                "errors": [{
                    "extensions": {
                        "value": null,
                        "problems": [{
                            "path": [],
                            "explanation": "Expected value to not be null"
                        }]
                    },
                    "locations": [{
                        "line": 2,
                        "column": 17
                    }],
                    "message": "Variable $id of type ID! was provided invalid value"
                }]
            },
            "traceId": "1eea08d3-b6d5-4c38-a1b0-cdb84b5d52ce"
        }
    }],
    "data": {
        "__typename": "Mutation",
        "gitHub": null
    }
}
```

### Desktop

- OS: all
- Browser: all
- Version: all

### Smartphone

- Device: all
- OS: all
- Browser: all
- Version: all

### Additional context

https://clips.twitch.tv/CuteDepressedPuffinWOOP-giOUmm9N_itsAVEo

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

The Repository page did not have the id for the issue available. This was removed while working a new feature that never shipped. 

- I add the issue number to the URL
- I now leverage that to identify the issue with the note. 

## Related Tickets & Documents

Fixes #955
Fixes #833

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 🙅 no documentation needed

### CODE REVIEW

File: src/components/ListGoals.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ function ListGoals({goals, data}) {
             <li key={goal.id}>
               <Link
                 to={{
-                  pathname: `/repos/${goal.full_name.replace(/\s+/g, "")}/`,
+                  pathname: `/repos/${goal.full_name.replace(/\s+/g, "")}/${goal.number}/`,
```
Comment (bdougie) [inline src/components/ListGoals.js:69]: This is the main change/fix.

File: src/components/Repository.js [hunk 2]
```diff
@@ -58,6 +58,7 @@ function Repository({user, match}) {
     api
       .persistedGoalFetch(parseInt(id))
       .then(res => {
+        console.log(res)
```
Comment (bdougie) [inline src/components/Repository.js:61]:
```suggestion
```
