### PR TITLE
526 set stars with new repo meta data

### LINKED ISSUE #526: Wrong stars count in homepage
Screenshot

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
This PR leverages the newly added data.json in the [goals-template/goals-caching.yml](https://github.com/open-sauced/goals-template/blob/master/.github/workflows/goals-caching.yml). This an effort add individual repo data without adding extra queries to the GitHub API. The fetching is offloaded to the user's own Action minutes ([2000 minute limit per month](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions)).

 #526 #384 

### Changes
- To properly merge the 2 fetched arrays from the `data.json` and repository issues. I renamed the `issue.title` to `issues.full_name`. 
- The FlexCenter style was being repeated, so I made the change to leverage that as the based style for a few other components.

### Additions
- [lodash](https://lodash.com/) for use of the merge function. I am open to suggestions for alternatives.

### Deletions
- none

## Related Tickets & Documents
- [goals-caching.yml](https://github.com/open-sauced/goals-template/blob/master/.github/workflows/goals-caching.yml)
- https://github.com/open-sauced/open-sauced/issues/526
- https://github.com/open-sauced/open-sauced/issues/384
- #660 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Screenshot 2020-06-13 05 44 49

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
I would like to address this in this PR, but if I don't get to it. It would provide an option for some to add re-sync the open-sauced-goals repo with the template. 

At the moment, the stars should not show if the user has not data.json.

### CODE REVIEW

**Comment by yg** [comment]
@bdougie Do this will break for old users, with old open-sauced-goals repo?

**Comment by bdougie** [comment]
Yes, I addressing that now. I wanted to get my thought and process out in the open before I started testing all scenarios. 

I want to add a feature to automate the open-sauced-goal repos to get updated when there is a new version. Not sure if I will address that in this or do a separate PR and merge that first.

File: src/components/RepositoryGoals.js [hunk 1]
```diff
@@ -45,6 +45,8 @@ function RepositoryGoals({user}) {
     dispatch({type: "UPDATE", payload: updatedRepos});
   };
 
+  const data = repository.data && JSON.parse(repository.data.text)
+
```
Comment (bdougie) [inline src/components/RepositoryGoals.js:49]: @yg this check here, to prevent the stars from showing if there is no data.json. 

I plan to do a similar check to sync the user's goals data.

**Comment by bdougie** [comment]
@yg any thoughts on this lint error in the PR? The log doesn't show an error, but it fails validation.

**Comment by yg** [comment]
@bdougie I have no ideas, there is already an open issue for this https://github.com/tinovyatkin/action-eslint/issues/100

**Comment by yg** [comment]
@bdougie Suggestion!

It would be great if we show some thing like **"sync in progress"**

Screenshot

**Comment by bdougie** [comment]
That is a great idea. I also need to humanize those star numbers.
