### PR TITLE
fix: adds margin to recommended card

### LINKED ISSUE #1044: Bug: Fix dashboard column spacing
### Describe the bug

Dashboard is next to repository recommendations.

### To Reproduce

1. Log in 

### Expected behavior

The spacing between the dashboard card and the repository recommendations should be similar to the spacing between dashboard and the add repository box.

### Screenshots

Screenshot 2021-06-16 at 23 22 42

### Desktop

- OS: All
- Browser: All

### PR DESCRIPTION
**Pull request by bdougie**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

A quick fix to bring back the margin. For now, it will be inline until I can think of a better way to style these recommendations. 

## Related Tickets & Documents

fixes #1044

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screen Shot 2021-06-18 at 2 57 13 PM
## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [x] 🙅 no documentation needed

### CODE REVIEW

File: src/components/RepositoryGoals.js [hunk 1]
```diff
@@ -94,7 +94,8 @@ function RepositoryGoals({user}) {
               </SpaceBetweenTop>
             </RepositoryContext>
 
-            <FlexColumn style={{flex: 1}}>
+            {/* TODO: This section is temporary and will need ne styles. Inline style ok for now */}
```
Comment (bdougie) [inline src/components/RepositoryGoals.js:97]:
```suggestion
```
