### PR TITLE
Show fork if the user is not the owner

### LINKED ISSUE #770: Bug: you can fork your own repos
### Describe the bug
With the addition of making forks right from Open Sauced. you can also fork your own project - not possible through GitHub, you can only fork to an org from your account.

### To Reproduce
1. Add a repo of yours from the Dashboard
1. Go to it, try to fork
1. It's weird 😕 
### Expected behavior
There should be a conditional statement, to check, if you are not the author of the project.

### Screenshots
screenshot of repo view

### Desktop
The platform doesn't matter

### PR DESCRIPTION
**Pull request by filiptronicek**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
Only show the fork button if the project is not under the same account as the user currently logged in.

## Related Tickets & Documents
Closes #770 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## What gif best describes this PR or how it makes you feel?
costumes nacho GIF by GIPHY CAM

### CODE REVIEW

**Comment by filiptronicek** [comment]
@yg, could you please help with making the tests pass?

File: src/components/Repository.js [hunk 1]
```diff
@@ -98,8 +98,11 @@ function Repository({match}) {
       .finally(() => setIsForkLoading(false));
   };
 
+
   const user = getUserFromJwt(Config.auth);
 
+  const showFork = repoOwner !== user.login ? true : isForkLoading;
```
Comment (yg) [inline src/components/Repository.js:104]: @filiptronicek Try this!

```suggestion
  const showFork = repoOwner !== user && user.login ? true : isForkLoading;
```

File: src/components/Repository.js [hunk 2]
```diff
@@ -164,11 +167,13 @@ function Repository({match}) {
               <a rel="noreferrer" target="_blank" href={`https://codetriage.com/${nameWithOwner}`}>
                 <Button primary>Set up CodeTriage</Button>
               </a>
-              {isForked ?
-                <a rel="noreferrer" target="_blank" href={`https://github.com/${user.login}/${repoName}`}>
-                  <Button disabled={isForkLoading} data-test="go-to-fork-button">View fork</Button>
-                </a> :
-                <Button disabled={isForkLoading} onClick={forkRepository}><RepoForkedIcon verticalAlign="middle" /> Fork</Button>}
+              { showFork ? (
```
Comment (yg) [inline src/components/Repository.js:170]: @filiptronicek Instead of ternary condition, we can use just use `showFork && (..` and remove null in else part!

**Comment by filiptronicek** [comment]
Weird, the tests still don't pass :( @yg

**Comment by filiptronicek** [comment]
Looks like it thinks. that user is still not defined or something https://github.com/open-sauced/open-sauced/pull/771/checks?check_run_id=838583322#step:5:202

**Comment by bdougie** [comment]
>Looks like it thinks. that user is still not defined or something https://github.com/open-sauced/open-sauced/pull/771/checks?check_run_id=838583322#step:5:202


@filiptronicek adding this the test Component will fix it.

**Comment by filiptronicek** [comment]
> 
> 
> > Looks like it thinks. that user is still not defined or something https://github.com/open-sauced/open-sauced/pull/771/checks?check_run_id=838583322#step:5:202
> 
> @filiptronicek adding this the test Component will fix it.

Can anyone help? I never did tests in React.

File: src/components/Repository.js [hunk 3]
```diff
@@ -98,8 +98,11 @@ function Repository({match}) {
       .finally(() => setIsForkLoading(false));
   };
 
+
   const user = getUserFromJwt(Config.auth);
```
Comment (bdougie) [inline src/components/Repository.js:102]: This needs to be mocked in the test @filiptronicek 

similar to https://github.com/open-sauced/open-sauced/blob/master/src/tests/App.test.js#L24

**Comment by bdougie** [comment]
Sorry I left off my link @filiptronicek 

https://github.com/open-sauced/open-sauced/blob/master/src/tests/App.test.js#L40

Adding the `data.user` to the props in the test will make it pass. 

In the Repository.test.js leverage something like [this jest mock **function](https://jestjs.io/docs/en/mock-functions) to get the `getJWTUser` function to return a user.

Right now it's failing on fetching the user in the test environment.

**Comment by filiptronicek** [comment]
I've tried a lot of solutions, am I placing the code right? Still returns the undefined error @yg @bdougie 
screenshot of code

```
TypeError: Cannot read property 'login' of undefined
```

File: src/components/Repository.js (hunk 3 above)
Comment (bdougie) [reply src/components/Repository.js:102]: Turns out this line should not be here. I did some work on this PR and got it working with mock and a spyOn. There is a rule I live by, which is if a test is hard to write the code can be refactored. 

I am going to open a PR to remove this.

**Comment by filiptronicek** [comment]
Here are my additions to the tests @bdougie

File: src/tests/Repository.test.js [hunk 4]
```diff
@@ -4,6 +4,8 @@ import Repository from "../components/Repository";
 import {data, match, location} from "./mocks";
 
 describe("<Repository />", () => {
+  const getUserFromJwt = jest.fn();
+  getUserFromJwt.mockReturnValueOnce({id:29888641,login:"filiptronicek"}).mockReturnValue(true);
```
Comment (bdougie) [inline src/tests/Repository.test.js]: This can be removed, I decoupled this function from this component in #777

File: src/tests/Repository.test.js [hunk 5]
```diff
@@ -4,6 +4,8 @@ import Repository from "../components/Repository";
...
   it("should render without throwing an error", () => {
     const component = shallow(<Repository location={location} match={match} data={data} />);
```
Comment (bdougie) [inline src/tests/Repository.test.js]: You will need to add the `data.user` here.

```suggestion
    const component = shallow(<Repository user={data.user} location={location} match={match} data={data} />);
```

File: src/tests/Repository.test.js (hunk 4 above)
Comment (filiptronicek) [reply src/tests/Repository.test.js]: Ok, removed them

File: src/tests/Repository.test.js (hunk 5 above)
Comment (filiptronicek) [reply src/tests/Repository.test.js]: Should I add it just to the first or also the second test? @bdougie

Comment (bdougie) [reply src/tests/Repository.test.js]: yes, it should be both :)

Comment (filiptronicek) [reply src/tests/Repository.test.js]: Ok, done, I hope it is ok now.

**Comment by filiptronicek** [comment]
Corrected some errors, should be ready for merge

**Comment by bdougie** [comment]
Thanks, @filiptronicek for working on this. Sorry, this testing issue sidetracked this change.

**Comment by filiptronicek** [comment]
I'm glad it works @bdougie :)
