### PR TITLE
Fix fork button

### LINKED ISSUE #783: Bug: The fork button is always disables
### Describe the bug

Not sure if this broke when merged, but the fork buttons seems to never work now and is always disabled. 

### To Reproduce

1. Navigate to a goal i.e. opensauced.pizza/repos/owner/repo/number
2. Fork the repo or view the fork if it exists. 

### Expected behavior

I should be able to fork a repo.

### Screenshots

Screenshot 2020-07-07 16 04 09

### PR DESCRIPTION
**Pull request by yg**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Fix fork button that is always disabled

And also fixed this https://github.com/open-sauced/open-sauced/pull/776#issuecomment-654842794

## Related Tickets & Documents

Closes #783

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

File: src/components/Repository.js [hunk 1]
```diff
@@ -169,12 +169,16 @@ function Repository({user, match}) {
               <a rel="noreferrer" target="_blank" href={`https://codetriage.com/${nameWithOwner}`}>
                 <Button primary>Set up CodeTriage</Button>
               </a>
-              { showFork && (
-                isForked ?
```
Comment (bdougie) [inline src/components/Repository.js:173]: good catch. I think my the merge conflict I fixed also removed this.

File: src/components/Repository.js [hunk 2]
```diff
@@ -169,12 +169,16 @@ function Repository({user, match}) {
...
+              {showFork &&
+                isForked ? (
```
Comment (bdougie) [inline src/components/Repository.js:173]: meant to put the comment here.

File: src/components/Repository.js [hunk 3]
```diff
@@ -96,7 +96,7 @@ function Repository({user, match}) {
       .finally(() => setIsForkLoading(false));
   };
 
-  const showFork = repoOwner !== user && user.login ? true : isForkLoading;
+  const showFork = repository && repoOwner !== user && user.login ? true : isForkLoading;
```
Comment (yg) [inline src/components/Repository.js:99]: Fixed this error https://sentry.io/share/issue/4aac93bccae04f929c6605724051260b/
