### PR TITLE
fix: weird spacing on the dashboard and repo screen

### LINKED ISSUE #1422: Bug: Weird spacing on the dashboard and repository screens
### Describe the bug

Screen Shot 2022-04-13 at 2 52 22 PM
Screen Shot 2022-04-13 at 2 52 18 PM

The left and right margin seem too much. this should match the top margin.

### Steps to reproduce

Visit the dashboard as a logged in user.

### Affected services

opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR removes margins between cards on the dashboard and repository screen

## Related Tickets & Documents

Fixes #1422 

| dashboard_before 	| dashboard_after 	|
|----------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------------	|
| repo_before      	| repo_after      	|

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: src/styles/Grid/Flex.js [hunk 1]
```diff
@@ -24,6 +24,10 @@ const FlexColumnCenter = styled(FlexCenter)`
 const FlexColumn = styled.div`
   display: flex;
   flex-direction: column;
+
+  .fpyAse {
```
Comment (0-vortex) [inline src/styles/Grid/Flex.js:28]: does this do anything? :D

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍 

Left minor question, can push this soon 🍕

File: src/styles/Grid/Flex.js (hunk 1 above)
Comment (TAKANOME-DEV) [reply src/styles/Grid/Flex.js:28]: Yeah the card in the FlexColumn has a marginTop, since it was used in many places(like onboarding i think), I didn't want to cause some layout issues that's way I added that 👆
