### PR TITLE
fix: malformed goal urls over 10

### LINKED ISSUE #1014: Bug: More than 10 Goals makes malformed URLs
### Describe the bug
If someone has more than 10 items in their goals list, any goals beyond the 10th one in the list will have "undefined" in the part of the URL where the issue number should be.  I haven't tracked down exactly how this happens, but I think that the initial state from the goals list uses [SWR](https://swr.vercel.app/) and comes up with greater than 10 line items, while some of the GraphQL queries used for this same list limit to the [first 10](https://github.com/open-sauced/open-sauced/blob/main/src/lib/apiGraphQL.js#L126).
```graphql
query FetchGoals() {
    gitHub {
      viewer {
        repository(name: "open-sauced-goals") {
          id
          data: object(expression: "HEAD:data.json") {
            id
            ... on GitHubBlob {
              id
              text
            }
          }
          issues(
            first: 10
            states: OPEN
            orderBy: { direction: DESC, field: CREATED_AT }
          ) {
            totalCount
            nodes {
              id
              full_name: title
              body
              number
              labels(first: 3) {
                nodes {
                  color
                  name
                  id
                }
              }
            }
          }
        }
      }
    }
  }
```

### To Reproduce
1) Make sure you have more than 10 line items in your goals list
2) Scroll down to 11th or later in the list. 
3) Validate URL ends in undefined.

### Expected behavior
Issue number is used in URL rather than "undefined"

### Screenshots
Screen Shot 2021-05-19 at 10 52 43 PM

### Desktop

- OS: macOS High Sierra
- Browser: Chrome

### Additional context

When I run locally, I also get a related error about the list in [ListGoals.js](https://github.com/open-sauced/open-sauced/blob/main/src/components/ListGoals.js#L66) needing to have a unique key, and this is due to the fact I have 12+ goal repos, so there's more than one without the goal.id variable set.

### PR DESCRIPTION
**Pull request by mtfoley**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
Fixes #1014  by bumping GQL to first 50 items.

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
punt

### CODE REVIEW

File: src/lib/apiGraphQL.js [hunk 1]
```diff
@@ -123,7 +123,7 @@ const operationsDoc = `
             }
           }
           issues(
-            first: 10
+            first: 50
```
Comment (bdougie) [inline src/lib/apiGraphQL.js:126]: LGTM

**Review by bdougie — APPROVED** [review]

**Comment by bdougie** [comment]
I realized the project used to limit all track repos to 10. Eventually, I need to set up logic to track a limited amount of repos. I think at the point you hit 50, the project is no longer useful. But this is something I can punt on for now.
