### PR TITLE
Resolves #754: centered logo across browsers

### LINKED ISSUE #754: Bug: bad logo alignment in menu
### Describe the bug
The Open Sauced logo is badly aligned in Firefox.

### Screenshots
| Chrome       | Firefox     |
| :------------- | :----------: |
| Chrome | Firefox |

### Desktop

- OS: Win 10
- Browser: Firefox Dev Edition
- Version: Latest

### PR DESCRIPTION
**Pull request by JapneetSingh5**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
The issue was observed in safari too. Chromium browsers rendered it just fine.
The logo is now centred across browsers, the solution uses a vertical-align on the image and bottom margin prop to make it perfectly centred. Even without the margin, it looks fine too.
Resolves #754 

## Related Tickets & Documents

https://github.com/open-sauced/open-sauced/issues/754

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screen Shot 2020-06-30 at 5 59 19 PM
Screen Shot 2020-06-30 at 5 59 05 PM
Screen Shot 2020-06-30 at 5 58 47 PM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

### CODE REVIEW

File: src/components/Nav.js [hunk 1]
```diff
@@ -17,9 +17,9 @@ function LeftSide({isLoggedIn, user, handleLogIn, handleLogOut}) {
   };
 
   return (
-    <FloatLeftMobileNav>
-      <Link style={{verticalAlign: "middle"}} to="/">
-        <img alt="open sauced" src={logo} />
+    <FloatLeftMobileNav >
+      <Link to="/" style={{display: "inline-block", verticalAlign: "middle"}}>
+        <img alt="open sauced" src={logo} style={{display: "inline-block", verticalAlign: "middle", marginBottom: 6}} />
```
Comment (yg) [inline src/components/Nav.js:22]: @JapneetSingh5 Moving to **styled-components** would be awesome!

Comment (JapneetSingh5) [reply src/components/Nav.js:22]: Oh okay. I don’t have much experience with styled-components, will find out how to use them.

Comment (JapneetSingh5) [reply src/components/Nav.js:22]: Oh right, they seem familiar. Do i create a new component named, say NavLogo and put all the styles in there?

Comment (yg) [reply src/components/Nav.js:22]: @JapneetSingh5 Instead of new comp! We can create a class called `.logo` inside `FloatLeftMobileNav`!

WDYT?

Comment (JapneetSingh5) [reply src/components/Nav.js]: Made a change, have a look.

File: src/components/Nav.js [hunk 2]
```diff
@@ -8,18 +8,24 @@ import ProfileAvatar from "../styles/ProfileAvatar";
...
 import Hotkeys from "react-hot-keys";
 import {useHistory, Link} from "react-router-dom";
+import styled from "styled-components";
 
 function LeftSide({isLoggedIn, user, handleLogIn, handleLogOut}) {
+  const Logo = styled.img`
+  display: "inline-block";
+  vertical-lign: "middle"; 
+  margin-bottom: 6;
+  `;
```
Comment (yg) [inline src/components/Nav.js:18]: @JapneetSingh5 I suggest you to move here https://github.com/open-sauced/open-sauced/blob/master/src/styles/Grid/Float.js#L9-L18

Comment (JapneetSingh5) [reply src/components/Nav.js:18]: I move the Logo as is there and import it into Nav.js right?

Comment (yg) [reply src/components/Nav.js:18]: That good idea @JapneetSingh5 👍 proceed it!

Comment (JapneetSingh5) [reply src/components/Nav.js]: Done that 🥳

File: src/styles/Grid/Float.js [hunk 3]
```diff
@@ -21,4 +21,10 @@ const FloatRight = styled.div`
   float: right;
 `;
 
-export {FloatRight, FloatLeft, FloatLeftMobileNav};
+const Logo = styled.img`
+  display: "inline-block";
+  vertical-lign: "middle"; 
+  margin-bottom: 6;
+  `;
```
Comment (yg) [inline src/styles/Grid/Float.js:28]:
```suggestion
const Logo = styled.img`
  display: "inline-block";
  vertical-lign: "middle"; 
  margin-bottom: 6;
`;
```

File: src/components/Nav.js [hunk 4]
```diff
@@ -17,9 +17,9 @@ function LeftSide({isLoggedIn, user, handleLogIn, handleLogOut}) {
   };
 
   return (
-    <FloatLeftMobileNav>
-      <Link style={{verticalAlign: "middle"}} to="/">
-        <img alt="open sauced" src={logo} />
+    <FloatLeftMobileNav >
+      <Link to="/" style={{verticalAlign: "middle", display: "inline-block"}}>
```
Comment (yg) [inline src/components/Nav.js:21]: @JapneetSingh5 Do we need to have style here?

Comment (JapneetSingh5) [reply src/components/Nav.js:21]: The display attr is required, gets messed up on removing it.
The vertical align style was already there, i didn't add it, i guess its fine keeping it inline here as it is unlikely this will be reused or will have an impact going forward.

File: src/components/Nav.js [hunk 5]
```diff
@@ -17,9 +17,9 @@ function LeftSide({isLoggedIn, user, handleLogIn, handleLogOut}) {
   };
 
   return (
-    <FloatLeftMobileNav>
-      <Link style={{verticalAlign: "middle"}} to="/">
-        <img alt="open sauced" src={logo} />
+    <FloatLeftMobileNav >
```
Comment (yg) [inline src/components/Nav.js:20]: @JapneetSingh5 Remove space here too!

```suggestion
    <FloatLeftMobileNav>
```
